import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AntdProvider from "@/layouts/AntdProvider";
import Provider from "@/redux/Provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<AntdProvider>
				<Provider>
					<body className="min-h-full flex flex-col">{children}</body>
				</Provider>
			</AntdProvider>
		</html>
	);
}
